manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: iwk7273
      url-base: https://github.com/iwk7273
  projects:
    - name: zmk
      remote: zmkfirmware
      # revision: main
      revision: v0.3
      import: app/west.yml
    - name: zmk-pmw3610-driver
      remote: iwk7273
      revision: main
      # revision: v0.3
    - name: zmk-feature-sensor_rotation
      remote: iwk7273
      revision: main
      # revision: v0.3
    - name: zmk-feature-xy_clipper
      remote: iwk7273
      revision: main
      # revision: v0.3
    - name: zmk-feature-scaling
      remote: iwk7273
      revision: main
      # revision: v0.3
  self:
    path: config
